name: Publish to Container Registry
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Podman
        run: |
          sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
          wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_$(lsb_release -rs)/Release.key -O Release.key
          sudo apt-key add - < Release.key
          sudo apt-get update -qq
          sudo apt-get -qq -y install podman

      - name: Docker meta (for metadata generation)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/guilhermofromsogeti/publish-packages/game
          tags: type=sha

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build container
        run: |
          podman build -t ${{ steps.meta.outputs.tags }} .
          podman push ${{ steps.meta.outputs.tags }}
